### ISSUE TITLE
App Crashing on ios 10.0.1, 10.0.2

### ISSUE THREAD

**Issue by Haideralee** [quiply/SaveImage#3]
it's crashing app when `saveImageToGallery` function called.

**Comment by SebastianSchirmer** [comment]
Could you provide some more information and details on what is happening exactly? E.g. what device, what OS and version, what are you doing when it's "crashing"? Some code snippet would also be helpful for understanding what is happening.

**Comment by Haideralee** [comment]
it's work fine on IOS < 10 and when i check on IOS >= 10 . it's crashing the app.i'm using iphone 6s and  downloading image through [cordova-plugin-file-transfer](https://github.com/apache/cordova-plugin-file-transfer) and then use `SaveImage` plugin to save image in photo Gallery.

**Comment by SebastianSchirmer** [comment]
@Haideralee We have just released an updated version 0.2.3 using which any iOS 10 issues should be resolved. Could you therefore please use this updated version and check if your issue is still occuring?

**Comment by Haideralee** [comment]
@leschirmeur ok let me check and i will surly inform you. if i will face any issue.

**Comment by Haideralee** [comment]
@leschirmeur Yeah it's working Thank You.
