### ISSUE TITLE
Phonegap Build

### ISSUE THREAD

**Issue by alij2016** [quiply/SaveImage#4]
Can you provide an example how to use it on Phonegap Build? I mean what is the file I must include in config.xml and also can I do it like: 

`var nativePathToJpegImage = 'ww/1.png'`

Then use onclick function like:
`
<img alt="Wallpaper" src="www/1.png" onclick="window.cordova.plugins.ImageSaver.saveImageToGallery();"/>`

**Comment by uaza** [comment]
If you use Phonegap it's probably a good idea to look into the plugin.xml what needs to be entered in the config.xml.

Your attempt to save the image in the onclick method is unfortunately not possible.
