### ISSUE TITLE
Create a Folder with app name

### ISSUE THREAD

**Issue by dhavalkakkad** [quiply/SaveImage#5]
Hi,

To start with, this is awesome plugin. Thanks a lot. 

What I want to say is, images are stored in gallery in my android in default **pictures** folder. Is it possible that I can create a folder with the name of my app in gallery and store images inside it ?

**Comment by dhavalkakkad** [comment]
Solved it, Thanks anyway :-)

**Comment by sajjadalis** [comment]
Hi @dhavalkakkad , how do you solved it. Can you show me full method you used. In my case, image is not saving at all anywhere. Though i would like to save all images to a custom name folder. This is how i'm trying.

```
function saveImg() {
    var nativePathToJpegImage = 'images/001.jpg'
    cordova.plugins.imagesaver.saveImageToGallery(nativePathToJpegImage, onSaveImageSuccess, onSaveImageError);
}
function onSaveImageSuccess() {
    console.log('success');
}                                         
function onSaveImageError(error) {
    console.log('error: ' + error);
}
$$('.save-img').on('click', function (e) {
     saveImg();
});
```

**Comment by gwenael-louandre** [comment]
Hi both,
did you find a solution for that point? I would like to save my pictures in a specific folder and not 'Pictures'.
Thanks

**Comment by dhavalkakkad** [comment]
Hi @Key7i and @gwenael-louandre ,

Its been a long time since I have worked on this, will check if I have saved the code. Will pass on if I found.

Cheers
