### ISSUE TITLE
Save base64 image direct to gallery

### ISSUE THREAD

**Issue by wwhyte** [quiply/SaveImage#7]
Feature request rather than issue: it would be great to be able to save the base64 stream you get from a camera call back straight to the gallery, rather than needing a path to a saved file. Would this be easy to add? I might have a shot at it myself but have limited time.

**Comment by SebastianSchirmer** [comment]
Hi William, thanks for your proposal. We have come up with this plugin to serve specific needs of our Quiply app where we had the need to access images via a path. We currently don't have the need to save a base64 stream directly and therefore won't invest time into that. However, please feel free to fork the plugin and give it a shot by yourself.
